### ISSUE TITLE
Toggle comment in fixed-form grammar

### ISSUE THREAD

**Issue by dpo** [dparkins/language-fortran#78]
What's the way to indicate how toggle comment should work (Command-/) in fixed-form source files? Currently, Command-/ inserts C-style comments. I tried adding this to my `config.cson`:
```
".fixed.fortran.source":
  editor:
    commentStart: "^C "
    commentEnd: ""
```
but clearly, that's not the way to insert a `C` in column 1... Any ideas?
